controllers/AddController.php
<?php

namespace app\controllers;

use app\models\forms\AddForm;
use yii\web\Controller;

class AddController extends Controller
{
    public function actionStandard()
    {
        $model = new AddForm();

        if ($model->load(\Yii::$app->request->post())) {

            if (\Yii::$app->request->post('add') == 1 && $model->add()) {
                return $this->goHome();
            }

            if (\Yii::$app->request->post('add') == 2 && $model->newList()) {
                return $this->goHome();
            }


        }

        return $this->render('add-new-list', [
            'model' => $model,
        ]);
    }
}

controllers/AppController.php
<?php

namespace app\controllers;

use app\models\forms\ChooseUserForm;
use app\models\helpers\FileDbHelpers;
use app\models\App\User;
use yii\web\Controller;

class AppController extends Controller
{
    public function actionChooseUser()
    {
        $db = FileDbHelpers::read(User::getUserlistFilename());

        $userlist = [];

        foreach ($db as $key => $value) {
            $userlist[$value] = $value;
        }

        $model = new ChooseUserForm();

        if ($model->load(\Yii::$app->request->post()) && $model->action()) {
            return $this->goHome();
        } else {
            return $this->render('choose-user', [
                'userlist' => $userlist,
                'model' => $model,
                'errors' => $model->errors,
            ]);
        }
    }
}

controllers/DbController.php
<?php

namespace app\controllers;

use app\models\App\User;
use app\models\forms\DbForm;
use app\models\helpers\DbHelpers;
use yii\web\Controller;

class DbController extends Controller
{
    public function actionSettings()
    {
        return $this->render('settings');
    }

    public function actionGo($actionType)
    {
        switch ($actionType) {
            case DbForm::DELETE_UNWORKING:

                \Yii::$app->db->createCommand()->delete("account-" . User::getActiveUser(), 'working = 0')->execute();
                DbHelpers::running();
                break;

            case DbForm::DELETE_BANNED:

                \Yii::$app->db->createCommand()->delete("account-" . User::getActiveUser(), "banned = 1 OR error_type = 'incorrect_password'")->execute();
                DbHelpers::running();
                break;

            case DbForm::UPDATE_PHOTO:

                \Yii::$app->db->createCommand()->update("account-" . User::getActiveUser(), ['photo' => 1])->execute();
                break;
        }

        $this->goHome();
    }
}

controllers/ProxyController.php
<?php

namespace app\controllers;

use app\models\forms\proxy\AddForm;
use app\models\Instagram\MobileProxy;
use yii\web\Controller;

class ProxyController extends Controller
{
    public function actionList()
    {
        $model = new AddForm();

        if ($model->load(\Yii::$app->request->post())) {
            $model->add();
        }

        $mobileProxyList = MobileProxy::find()->all();

        return $this->render('list', [
            'model' => $model,
            'mobileProxyList' => $mobileProxyList,
            'errors' => $model->errors,
        ]);
    }
}

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\models\App\User;
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
    NavBar::begin([
        'brandLabel' => User::getActiveUser() . ' | <span class="text-success">' . \app\models\Instagram\Account::find()->where('working = 1')->count("*") . '</span> | <span class="text-warning">' . \app\models\Instagram\Account::find()->where('working = 0')->count("*") . '</span>',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);
    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'items' => [
            ['label' => 'Добавить новый список', 'url' => ['/add/standard']],

            [
                'label' => 'Настройки',
                'items' => [
                    ['label' => 'Управление аккаунтами', 'url' => '/db/settings'],
                    ['label' => 'Файлы для заполнения', 'url' => '/control-custom-files/file-list'],
                    ['label' => 'Выбор и добавление базы', 'url' => '/app/choose-user'],
                    ['label' => 'Мобильные прокси', 'url' => '/proxy/list'],
                ],
            ],

            [
                'label' => 'Выгрузка',
                'items' => [
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Тип выгрузки</li>',
                    ['label' => 'Standard', 'url' => '/account-list/standard'],
                    ['label' => 'SocialKit', 'url' => '/account-list/socialkit'],
                    ['label' => 'Instap', 'url' => '/account-list/instap'],
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Сломанные аккаунты</li>',
                    ['label' => 'SMS', 'url' => '/account-list/sms'],
                    ['label' => 'Email', 'url' => '/account-list/email'],
                    ['label' => 'Biography', 'url' => '/account-list/biography'],
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Заполненные аккаунты</li>',
                    ['label' => 'Filled', 'url' => '/account-list/filled'],
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Дополнительные стандарты</li>',
                    ['label' => 'Zaliv', 'url' => '/account-list/zaliv'],
                    '<li class="divider"></li>',
                    '<li class="dropdown-header">Список проокси</li>',
                    ['label' => 'Прокси забаненных аккаунтов', 'url' => '/account-list/banned'],
                    ['label' => 'Нерабочие прокси', 'url' => '/account-list/unknown'],
                ],
            ],
        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">Булат Гарипов</p>

        <p class="pull-right"></p>
    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>